branches:
  only:
    - master
language: go
go:
  - "1.11"
  - "1.15"
  - "1.16"
  - tip
install:
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u golang.org/x/lint/golint
  - make -v
  - make deps
  - go build -v ./...
script:
  - make check
